version: '3'
services:
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - OPENWEATHERMAP_API_KEY=
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api
